version: '3.8'

services:
  builder:
    build: .
    container_name: ai-upgrader-builder
    ports:
      - "${PORT:-8002}:${PORT:-8002}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-8002}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.3}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-3000}
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8002}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - ai-upgrader-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '1'
        reservations:
          memory: 512MB
          cpus: '0.5'

networks:
  ai-upgrader-network:
    driver: bridge